# Generated by Django 6.0.4 on 2026-04-18 14:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('latin_name', models.CharField(blank=True, max_length=100, verbose_name='Латинское название')),
                ('icon', models.CharField(default='🌱', max_length=4, verbose_name='Иконка (эмодзи)')),
                ('watering_interval_days', models.PositiveIntegerField(default=7, verbose_name='Интервал полива (дней)')),
                ('repotting_interval_days', models.PositiveIntegerField(default=730, verbose_name='Интервал пересадки (дней)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид растения',
                'verbose_name_plural': 'Виды растений',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя растения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='plants/', verbose_name='Фото')),
                ('last_watered', models.DateField(default=datetime.date.today, verbose_name='Последний полив')),
                ('last_repotted', models.DateField(default=datetime.date.today, verbose_name='Последняя пересадка')),
                ('is_alive', models.BooleanField(default=True, verbose_name='Живо')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('plant_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='plants.planttype', verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Растение',
                'verbose_name_plural': 'Растения',
                'ordering': ['-is_alive', 'last_watered'],
            },
        ),
    ]
