# Generated by Django 6.0.4 on 2026-04-18 13:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя растения')),
                ('species', models.CharField(blank=True, max_length=100, verbose_name='Вид / сорт')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='plants/', verbose_name='Фото')),
                ('watering_interval_days', models.PositiveIntegerField(default=7, verbose_name='Интервал полива (дней)')),
                ('last_watered', models.DateField(default=datetime.date.today, verbose_name='Последний полив')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Растение',
                'verbose_name_plural': 'Растения',
                'ordering': ['last_watered'],
            },
        ),
    ]
